// <auto-generated />
namespace AutoSherpa_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class newPSfChange1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newPSfChange1));
        
        string IMigrationMetadata.Id
        {
            get { return "202007051316383_newPSfChange1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
